from typing import Dict, NamedTuple, Set, Optional, Union
from .names_regions import RegionNames as rname


class ID2LocationData(NamedTuple):
    region: str
    location_id_offset: Union[int, None]
    location_group: Optional[str] = None


location_base_id = 238492834

location_table: Dict[str, ID2LocationData] = {
    # Each area gets 100 reserved location IDs
    # 0: Fluffy Fields
    "Fluffy Fields Caves - Goldbun Combat Chest": ID2LocationData(rname.ffc_b.value, 0),
    "Fluffy Fields Caves - Portal Room Chest": ID2LocationData(rname.ffc_c.value, 1),
    "Fluffy Fields Caves - Timed Bridge Chest": ID2LocationData(rname.ffc_e.value, 2),
    "Fluffy Fields Caves - Hermit Hint Chest": ID2LocationData(rname.ffc_f.value, 3),
    "Fluffy Fields Caves - Laser Chest": ID2LocationData(rname.ffc_g.value, 4),
    "Fluffy Fields Caves - Number Blocks Chest": ID2LocationData(rname.ffc_j.value, 5),
    "Fluffy Fields Caves - Ice Blockade Chest": ID2LocationData(rname.ffc_k.value, 6),
    "Fluffy Fields Caves - Double Spikebun Combat Chest": ID2LocationData(rname.ffc_m.value, 7),
    "Fluffy Fields Caves - Potion Bar Chest": ID2LocationData(rname.ffc_p.value, 8),
    "Fluffy Fields Caves - Six Buns Combat Chest": ID2LocationData(rname.ffc_q.value, 9),
    "Fluffy Fields Caves - Artist Backroom Chest": ID2LocationData(rname.ffc_x2.value, 10),
    "Fluffy Fields Caves - Jenny Berry House Outfit": ID2LocationData(rname.ffc_u.value, 11, "Super Secrets"),
    "Fluffy Fields Caves - Incomplete Sign": ID2LocationData(rname.ffc_h.value, 12, "Incomplete Signs"),
    "Fluffy Fields Caves - Cipher Sign": ID2LocationData(rname.ffc_u2.value, 13, "Cipher Signs"),
    # 100: Sweetwater Coast
    "Sweetwater Coast Caves - White Gates Combat Chest": ID2LocationData(rname.scc_b.value, 100),
    "Sweetwater Coast Caves - Feral Gates Combat Chest": ID2LocationData(rname.scc_g.value, 101),
    "Sweetwater Coast Caves - Three Teleporters Chest": ID2LocationData(rname.scc_h.value, 102),
    "Sweetwater Coast Caves - Four Candy Snakes Combat Chest": ID2LocationData(rname.scc_i.value, 103),
    "Sweetwater Coast Caves - Portal Spikes Chest": ID2LocationData(rname.scc_j.value, 104),
    "Sweetwater Coast Caves - Hint Hermit Chest": ID2LocationData(rname.scc_k.value, 105),
    "Sweetwater Coast Caves - Fake Chest Cave Chest": ID2LocationData(rname.scc_l.value, 106),
    "Sweetwater Coast Caves - Wooden Balls Spike Floor Chest": ID2LocationData(rname.scc_m.value, 107),
    "Sweetwater Coast Caves - Kung Fu Jenny Chest": ID2LocationData(rname.scc_n.value, 108),
    "Sweetwater Coast Caves - Incomplete Sign": ID2LocationData(rname.ssc_d.value, 109, "Incomplete Signs"),
    # 200: Fancy Ruins
    "Fancy Ruins Caves - Two Torches Chest": ID2LocationData(rname.frc_a.value, 200),
    "Fancy Ruins Caves - Numbered Torches Chest": ID2LocationData(rname.frc_b.value, 201),
    "Fancy Ruins Caves - Two Crystals Chest": ID2LocationData(rname.frc_c.value, 202),
    "Fancy Ruins Caves - Big Ogler Combat Chest": ID2LocationData(rname.frc_d.value, 203),
    "Fancy Ruins Caves - Hint Turnip Chest": ID2LocationData(rname.frc_g.value, 204),
    "Fancy Ruins Caves - Rhythm Pillars Chest": ID2LocationData(rname.frc_h.value, 205),
    "Fancy Ruins Caves - Teleporter Puzzle Chest": ID2LocationData(rname.frc_i.value, 206),
    "Fancy Ruins Caves - Four Oglers Combat Chest": ID2LocationData(rname.frc_j.value, 207),
    "Fancy Ruins Caves - Spike Path Chest": ID2LocationData(rname.frc_k.value, 208),
    "Fancy Ruins Caves - Hiding Hermit Chest": ID2LocationData(rname.frc_l.value, 209),
    "Fancy Ruins Caves - Ice and Torch Chest": ID2LocationData(rname.frc_m.value, 210),
    # 300: Star Woods
    "Star Woods Caves - Turnip Combat Chest": ID2LocationData(rname.swc_a.value, 300),
    "Star Woods Caves - Barrel Blast Chest": ID2LocationData(rname.swc_b.value, 301),
    "Star Woods Caves - Four Crystals Chest": ID2LocationData(rname.swc_c.value, 302),
    "Star Woods Caves - Sleeping Safety Jenny Chest": ID2LocationData(rname.swc_d.value, 303),
    "Star Woods Caves - Rotating Spikes Chest": ID2LocationData(rname.swc_f.value, 304),
    "Star Woods Caves - Number Tiles Chest": ID2LocationData(rname.swc_g.value, 305),
    "Star Woods Caves - Whirlwind Chest": ID2LocationData(rname.swc_h.value, 306),
    "Star Woods Caves - Magic Crystal Chest": ID2LocationData(rname.swc_i.value, 307),
    "Star Woods Caves - Artist Turnip Chest": ID2LocationData(rname.swc_j.value, 308),
    "Star Woods Caves - Hint Bee Chest": ID2LocationData(rname.swc_k.value, 309),
    "Star Woods Caves - Extinguish Flames Chest": ID2LocationData(rname.swc_o.value, 310),
    # 400: Slippery Slope
    "Slippery Slope Caves - Volcanic Path Chest": ID2LocationData(rname.ssc_a.value, 400),
    "Slippery Slope Caves - Ice and Barrels Chest": ID2LocationData(rname.ssc_b.value, 401),
    "Slippery Slope Caves - Eight Crystals Chest": ID2LocationData(rname.ssc_d.value, 402),
    "Slippery Slope Caves - Forgetful Jennies Chest": ID2LocationData(rname.ssc_e.value, 403),
    "Slippery Slope Caves - Push the Crystals Chest": ID2LocationData(rname.ssc_f.value, 404),
    "Slippery Slope Caves - Exhausted Turnip Chest": ID2LocationData(rname.ssc_g.value, 405),
    "Slippery Slope Caves - Bee Nest Combat Chest": ID2LocationData(rname.ssc_i.value, 406),
    "Slippery Slope Caves - Pushable Fan Chest": ID2LocationData(rname.ssc_j.value, 407),
    "Slippery Slope Caves - Moving Crystals Chest": ID2LocationData(rname.ssc_k.value, 408),
    "Slippery Slope Caves - Shark House": ID2LocationData(rname.ssc_l.value, 409),
    # 500: Pepperpain
    "Pepperpain Caves - Cowbun Combat Chest": ID2LocationData(rname.ppc_a.value, 500),
    "Pepperpain Caves - Brutus Combat Chest": ID2LocationData(rname.ppc_b.value, 501),
    "Pepperpain Caves - Torch Disappearing Path Chest": ID2LocationData(rname.ppc_f.value, 502),
    "Pepperpain Caves - Spiky Hint Bee Chest": ID2LocationData(rname.ppc_g.value, 503),
    "Pepperpain Caves - Cannon Path Chest": ID2LocationData(rname.ppc_h.value, 504),
    "Pepperpain Caves - Volcano Trail Chest": ID2LocationData(rname.ppc_j.value, 505),
    "Pepperpain Caves - Barrel Hint Bee Chest": ID2LocationData(rname.ppc_k.value, 506),
    "Pepperpain Caves - Haunted Guns Chest": ID2LocationData(rname.ppc_l.value, 507),
    "Pepperpain Caves - Buzzsaw Path Chest": ID2LocationData(rname.ppc_o.value, 508),
    "Pepperpain Caves - Number Tiles Chest": ID2LocationData(rname.ppc_p.value, 509),
    "Pepperpain Caves - Pacifist Brute Chest": ID2LocationData(rname.ppc_u.value, 510),
    "Pepperpain Caves - Incomplete Sign": ID2LocationData(rname.ppc_e.value, 511, "Incomplete Signs"),
    # 600: Frozen Court
    "Frozen Court Caves - Bushfire Chest": ID2LocationData(rname.fcc_a.value, 600),
    "Frozen Court Caves - Cannon Spinner Chest": ID2LocationData(rname.fcc_b.value, 601),
    "Frozen Court Caves - Mimicbuns Combat Chest": ID2LocationData(rname.fcc_c.value, 602),
    "Frozen Court Caves - Teleporter Maze Chest": ID2LocationData(rname.fcc_e.value, 603),
    "Frozen Court Caves - Chilly Roger Combat Chest": ID2LocationData(rname.fcc_f.value, 604),
    "Frozen Court Caves - Rickety Bridge Chest": ID2LocationData(rname.fcc_h.value, 605),
    "Frozen Court Caves - Titans Combat Chest": ID2LocationData(rname.fcc_i.value, 606),
    "Frozen Court Caves - Crystal Path Chest": ID2LocationData(rname.fcc_j.value, 607),
    "Frozen Court Caves - Teleporter Grate Chest": ID2LocationData(rname.fcc_k.value, 608),
    "Frozen Court Caves - Hint Hermit Chest": ID2LocationData(rname.fcc_l.value, 609),
    "Frozen Court Caves - Cipher Sign": ID2LocationData(rname.fcc_p.value, 610, "Cipher Signs"),
    # 700: Lonely Road
    "Lonely Road Caves - Timed Platforms Chest": ID2LocationData(rname.lrc_b.value, 700),
    "Lonely Road Caves - Timed Number Tiles Chest": ID2LocationData(rname.lrc_c.value, 701),
    "Lonely Road Caves - Volcano Chest": ID2LocationData(rname.lrc_d.value, 702),
    "Lonely Road Caves - Lava Fans Chest": ID2LocationData(rname.lrc_k.value, 703),
    "Lonely Road Caves - Force Turrets Chest": ID2LocationData(rname.lrc_m.value, 704),
    "Lonely Road Caves - Hint Shark Chest": ID2LocationData(rname.lrc_p.value, 705),
    "Lonely Road Caves - Teleporter Cube Chest": ID2LocationData(rname.lrc_r.value, 706),
    "Lonely Road Caves - Dark Maze Chest": ID2LocationData(rname.lrc_s.value, 707),
    "Lonely Road Caves - Block Factory": ID2LocationData(rname.lrc_t.value, 708),
    "Lonely Road Caves - Incomplete Sign": ID2LocationData(rname.lrc_i_right, 709, "Cipher Signs"),
    # 800: Pillow Fort
    "Pillow Fort - Treasure Chest": ID2LocationData(rname.d1_i.value, 800, "Dungeons"),
    "Pillow Fort - Shellbun Nest Key": ID2LocationData(rname.d1_j.value, 801, "Dungeons"),
    "Pillow Fort - Crayon Chest": ID2LocationData(rname.d1_g.value, 802, "Dungeons"),
    "Pillow Fort - Safety Jenny Gate Key": ID2LocationData(rname.d1_e.value, 803, "Dungeons"),
    "Pillow Fort - Boss Reward Chest": ID2LocationData(rname.d1_c.value, 804, "Dungeons"),
    # 900: Sand Castle
    "Sand Castle - Crayon Chest": ID2LocationData(rname.d2_g.value, 900, "Dungeons"),
    "Sand Castle - Orbiting Balls Key": ID2LocationData(rname.d2_i.value, 901, "Dungeons"),
    "Sand Castle - Spikebun Dunes Key": ID2LocationData(rname.d2_d.value, 902, "Dungeons"),
    "Sand Castle - Treasure Chest": ID2LocationData(rname.d2_j.value, 904, "Dungeons"),
    "Sand Castle - Boss Reward Chest": ID2LocationData(rname.d2_a.value, 905, "Dungeons"),
    # 1000: Art Exhibit
    "Art Exhibit - Entry Combat Key": ID2LocationData(rname.d3_r.value, 1000, "Dungeons"),
    "Art Exhibit - Evil Easels Key": ID2LocationData(rname.d3_n.value, 1001, "Dungeons"),
    "Art Exhibit - Treasure Chest": ID2LocationData(rname.d3_l.value, 1002, "Dungeons"),
    "Art Exhibit - Crayon Chest": ID2LocationData(rname.d3_f.value, 1003, "Dungeons"),
    "Art Exhibit - Spike Floor Key": ID2LocationData(rname.d3_e.value, 1004, "Dungeons"),
    "Art Exhibit - Business Casual Man Key": ID2LocationData(rname.d3_a.value, 1005, "Dungeons"),
    "Art Exhibit - Boss Reward Chest": ID2LocationData(rname.d3_d.value, 1006, "Dungeons"),
    # 1100: Trash Cave
    "Trash Cave - Crayon Chest": ID2LocationData(rname.d4_m.value, 1100, "Dungeons"),
    "Trash Cave - Ice Barricade Key": ID2LocationData(rname.d4_n_lower.value, 1101, "Dungeons"),
    "Trash Cave - Rotnip Combat Key": ID2LocationData(rname.d4_g_left.value, 1102, "Dungeons"),
    "Trash Cave - Treasure Chest": ID2LocationData(rname.d4_d.value, 1103, "Dungeons"),
    "Trash Cave - Mimic Combat Key": ID2LocationData(rname.d4_h.value, 1104, "Dungeons"),
    "Trash Cave - Block Maze Key": ID2LocationData(rname.d4_e.value, 1105, "Dungeons"),
    "Trash Cave - Boss Reward Chest": ID2LocationData(rname.d4_b.value, 1106, "Dungeons"),
    # 1200: Flooded Basement
    "Flooded Basement - Portal Cube Key": ID2LocationData(rname.d5_a.value, 1200, "Dungeons"),
    "Flooded Basement - Crossway Combat Key": ID2LocationData(rname.d5_l.value, 1201, "Dungeons"),
    "Flooded Basement - Land Sharks Key": ID2LocationData(rname.d5_u.value, 1202, "Dungeons"),
    "Flooded Basement - Treasure Chest": ID2LocationData(rname.d5_h.value, 1203, "Dungeons"),
    "Flooded Basement - Crayon Chest": ID2LocationData(rname.d5_g.value, 1204, "Dungeons"),
    "Flooded Basement - Keeled Fishbun Key": ID2LocationData(rname.d5_r.value, 1205, "Dungeons"),
    "Flooded Basement - Number Blocks Key": ID2LocationData(rname.d5_m.value, 1206, "Dungeons"),
    "Flooded Basement - Boss Reward Chest": ID2LocationData(rname.d5_c.value, 1207, "Dungeons"),
    # 1300: Potassium Mine
    "Potassium Mine - Hub Room Key": ID2LocationData(rname.d6_m.value, 1300, "Dungeons"),
    "Potassium Mine - South conveyor Key": ID2LocationData(rname.d6_t.value, 1301, "Dungeons"),
    "Potassium Mine - Crayon Chest": ID2LocationData(rname.d6_h.value, 1302, "Dungeons"),
    "Potassium Mine - West Minecart Track Key": ID2LocationData(rname.d6_l.value, 1303, "Dungeons"),
    "Potassium Mine - Number Tiles Key": ID2LocationData(rname.d6_n.value, 1304, "Dungeons"),
    "Potassium Mine - Treasure Chest": ID2LocationData(rname.d6_j.value, 1305, "Dungeons"),
    "Potassium Mine - Ice Tutorial Key": ID2LocationData(rname.d6_d.value, 1306, "Dungeons"),
    "Potassium Mine - Boss Reward Chest": ID2LocationData(rname.d6_a.value, 1307, "Dungeons"),
    # 1400: Boiling Grave
    "Boiling Grave - Skullnips Combat Key": ID2LocationData(rname.d7_t.value, 1400, "Dungeons"),
    "Boiling Grave - Titans Combat Key": ID2LocationData(rname.d7_z.value, 1401, "Dungeons"),
    "Boiling Grave - Treasure Chest": ID2LocationData(rname.d7_w.value, 1402, "Dungeons"),
    "Boiling Grave - Roll Pillars Key": ID2LocationData(rname.d7_o.value, 1403, "Dungeons"),
    "Boiling Grave - Royal Tomb Key": ID2LocationData(rname.d7_k.value, 1404, "Dungeons"),
    "Boiling Grave - Crayon Chest": ID2LocationData(rname.d7_b.value, 1405, "Dungeons"),
    "Boiling Grave - Chilly Roger Combat Key": ID2LocationData(rname.d7_d.value, 1406, "Dungeons"),
    "Boiling Grave - Boss Reward Chest": ID2LocationData(rname.d7_e.value, 1407, "Dungeons"),
    # 1500: Grand Library
    "Grand Library - Treasure Chest": ID2LocationData(rname.d8_g.value, 1500, "Dungeons"),
    "Grand Library - Crayon Chest": ID2LocationData(rname.d8_aa.value, 1501, "Dungeons"),
    "Grand Library - Patient Key": ID2LocationData(rname.d8_ac.value, 1502, "Dungeons"),
    "Grand Library - Hidden Key": ID2LocationData(rname.d8_t.value, 1503, "Dungeons"),
    "Grand Library - Fighter's Combat Key": ID2LocationData(rname.d8_ad.value, 1504, "Dungeons"),
    "Grand Library - Storied Key": ID2LocationData(rname.d8_ae.value, 1505, "Dungeons"),
    "Grand Library - Delayed Key": ID2LocationData(rname.d8_u.value, 1506, "Dungeons"),
    "Grand Library - Carrot Lobotomy Key": ID2LocationData(rname.d8_ab.value, 1507, "Dungeons"),
    "Grand Library - Crystals and Buttons Key": ID2LocationData(rname.d8_q.value, 1508, "Dungeons"),
    "Grand Library - Hexrot Combat Key": ID2LocationData(rname.d8_a.value, 1509, "Dungeons"),
    "Grand Library - Boss Key Chest": ID2LocationData(rname.d8_e.value, 1510, "Dungeons"),
    "Grand Library - Boss Reward Chest": ID2LocationData(rname.d8_rewards.value, 1511, "Dungeons"),
    "Grand Library - Extra Boss Reward Chest": ID2LocationData(rname.d8_rewards.value, 1512, "Dungeons"),
    # 1600: Sunken Labyrinth
    "Sunken Labyrinth - Gold Titan Combat Key": ID2LocationData(rname.s1_e.value, 1600, "Secret Dungeons"),
    "Sunken Labyrinth - Death Ogler Combat Key": ID2LocationData(rname.s1_c.value, 1601, "Secret Dungeons"),
    "Sunken Labyrinth - Treasure Chest": ID2LocationData(rname.s1_j.value, 1602, "Secret Dungeons"),
    "Sunken Labyrinth - Mimic Combat Key": ID2LocationData(rname.s1_o.value, 1603, "Secret Dungeons"),
    "Sunken Labyrinth - Crayon Chest": ID2LocationData(rname.s1_u.value, 1604, "Secret Dungeons"),
    "Sunken Labyrinth - Boss Reward Chest": ID2LocationData(rname.s1_g.value, 1605, "Secret Dungeons"),
    # 1700: Machine Fortress
    "Machine Fortress - Hyperdusa conveyor Key": ID2LocationData(rname.s2_l.value, 1700, "Secret Dungeons"),
    "Machine Fortress - Bee Chest": ID2LocationData(rname.s2_o.value, 1701, "Secret Dungeons"),
    "Machine Fortress - Crayon Chest": ID2LocationData(rname.s2_m.value, 1702, "Secret Dungeons"),
    "Machine Fortress - Number Tiles Key": ID2LocationData(rname.s2_h.value, 1703, "Secret Dungeons"),
    "Machine Fortress - Cannon conveyors Key": ID2LocationData(rname.s2_f.value, 1704, "Secret Dungeons"),
    "Machine Fortress - Light Bridge Key": ID2LocationData(rname.s2_e.value, 1705, "Secret Dungeons"),
    "Machine Fortress - Steel Skullnip Combat Key": ID2LocationData(rname.s2_d.value, 1706, "Secret Dungeons"),
    "Machine Fortress - Treasure Chest": ID2LocationData(rname.s2_b.value, 1707, "Secret Dungeons"),
    "Machine Fortress - Boss Reward Chest": ID2LocationData(rname.s2_g.value, 1708, "Secret Dungeons"),
    # 1800: Dark Hypostyle
    "Dark Hypostyle - Initial Key": ID2LocationData(rname.s3_a.value, 1800, "Secret Dungeons"),
    "Dark Hypostyle - Crayon Chest": ID2LocationData(rname.s3_v_upper.value, 1801, "Secret Dungeons"),
    "Dark Hypostyle - Blue Path Key": ID2LocationData(rname.s3_t.value, 1802, "Secret Dungeons"),
    "Dark Hypostyle - Yellow Path Monochrome Key": ID2LocationData(rname.s3_p.value, 1803, "Secret Dungeons"),
    "Dark Hypostyle - Treasure Chest": ID2LocationData(rname.s3_q.value, 1804, "Secret Dungeons"),
    "Dark Hypostyle - Yellow Path Key": ID2LocationData(rname.s3_l.value, 1805, "Secret Dungeons"),
    "Dark Hypostyle - Red Path Cannon Key": ID2LocationData(rname.s3_h.value, 1806, "Secret Dungeons"),
    "Dark Hypostyle - Red Path Key": ID2LocationData(rname.s3_g.value, 1807, "Secret Dungeons"),
    "Dark Hypostyle - Boss Reward Chest": ID2LocationData(rname.s3_d.value, 1808, "Secret Dungeons"),
    # 1900: Tomb of Simulacrum
    "Tomb of Simulacrum - Mercury Jello Number Tiles Key": ID2LocationData(rname.s4_ak.value, 1900, "Secret Dungeons"),
    "Tomb of Simulacrum - Self Locked Tile Key": ID2LocationData(rname.s4_af.value, 1901, "Secret Dungeons"),
    "Tomb of Simulacrum - Eight Tile Key": ID2LocationData(rname.s4_ab.value, 1902, "Secret Dungeons"),
    "Tomb of Simulacrum - Roundabout Crystal Key": ID2LocationData(rname.s4_u.value, 1903, "Secret Dungeons"),
    "Tomb of Simulacrum - Corner Torch Key": ID2LocationData(rname.s4_q.value, 1904, "Secret Dungeons"),
    "Tomb of Simulacrum - Crayon Chest": ID2LocationData(rname.s4_ac.value, 1905, "Secret Dungeons"),
    "Tomb of Simulacrum - Death Ogler Combat Key": ID2LocationData(rname.s4_ai.value, 1906, "Secret Dungeons"),
    "Tomb of Simulacrum - EFCS Door Key": ID2LocationData(rname.s4_s.value, 1907, "Secret Dungeons"),
    "Tomb of Simulacrum - Large Chasm Key": ID2LocationData(rname.s4_y.value, 1908, "Secret Dungeons"),
    "Tomb of Simulacrum - Spiked Orbitals Key": ID2LocationData(rname.s4_t.value, 1909, "Secret Dungeons"),
    "Tomb of Simulacrum - Molten Conveyors Key": ID2LocationData(rname.s4_aq.value, 1910, "Secret Dungeons"),
    "Tomb of Simulacrum - Treasure Chest": ID2LocationData(rname.s4_i.value, 1911, "Secret Dungeons"),
    "Tomb of Simulacrum - Boss Reward Chest": ID2LocationData(rname.s4_g.value, 1912, "Secret Dungeons"),
    # 2000: Syncope
    "Syncope - Shifting Chamber Key": ID2LocationData(rname.dd_sc.value, 2000, "Dreamworld"),
    "Syncope - Switch Chamber Card": ID2LocationData(rname.dd_am.value, 2001, "Dreamworld"),
    "Syncope - Foyer Card": ID2LocationData(rname.dd_z.value, 2002, "Dreamworld"),
    "Syncope - Garden Key": ID2LocationData(rname.dd_n.value, 2003, "Dreamworld"),
    "Syncope - Piano Card": ID2LocationData(rname.dd_k.value, 2004, "Dreamworld"),
    "Syncope - Knights Hint Card": ID2LocationData(rname.dd_c.value, 2005, "Dreamworld"),
    "Syncope - Shadow Walker Key": ID2LocationData(rname.dd_d_left.value, 2006, "Dreamworld"),
    "Syncope - Force Turret Maze Card": ID2LocationData(rname.dd_v.value, 2007, "Dreamworld"),
    "Syncope - Reward Card A": ID2LocationData(rname.dd_ao.value, 2008, "Dreamworld"),
    "Syncope - Reward Card B": ID2LocationData(rname.dd_ao.value, 2009, "Dreamworld"),
    "Syncope - Reward Card C": ID2LocationData(rname.dd_ao.value, 2010, "Dreamworld"),

    # 2100: Wizardry Lab
    "Wizardry Lab - Entrance Card": ID2LocationData(rname.df_ad.value, 2100, "Dreamworld"),
    "Wizardry Lab - West Energy Source Card": ID2LocationData(rname.df_w.value, 2101, "Dreamworld"),
    "Wizardry Lab - Cannon Card": ID2LocationData(rname.df_c.value, 2102, "Dreamworld"),
    "Wizardry Lab - East Mirrors Card": ID2LocationData(rname.df_m_bottom.value, 2103, "Dreamworld"),
    "Wizardry Lab - East Energy Source Card": ID2LocationData(rname.df_aa.value, 2104, "Dreamworld"),
    "Wizardry Lab - Reward Card A": ID2LocationData(rname.df_ah.value, 2105, "Dreamworld"),
    "Wizardry Lab - Reward Card B": ID2LocationData(rname.df_ah.value, 2106, "Dreamworld"),
    "Wizardry Lab - Reward Card C": ID2LocationData(rname.df_ah.value, 2107, "Dreamworld"),

    # 2200: Antigram
    "Antigram - Free Key": ID2LocationData(rname.dfc_r.value, 2200, "Dreamworld"),
    "Antigram - West Light Bridge Card": ID2LocationData(rname.dfc_p.value, 2201, "Dreamworld"),
    "Antigram - East Light Bridge Card": ID2LocationData(rname.dfc_r.value, 2202, "Dreamworld"),
    "Antigram - West Ice Card": ID2LocationData(rname.dfc_k.value, 2203, "Dreamworld"),
    "Antigram - East Ice Card": ID2LocationData(rname.dfc_o.value, 2204, "Dreamworld"),
    "Antigram - West Bombs Key": ID2LocationData(rname.dfc_b.value, 2205, "Dreamworld"),
    "Antigram - East Bombs Key": ID2LocationData(rname.dfc_d.value, 2206, "Dreamworld"),
    "Antigram - End East Bridge Card": ID2LocationData(rname.dfc_e.value, 2207, "Dreamworld"),
    "Antigram - End West Bridge Key": ID2LocationData(rname.dfc_e.value, 2208, "Dreamworld"),
    "Antigram - Reward Card A": ID2LocationData(rname.dfc_a.value, 2209, "Dreamworld"),
    "Antigram - Reward Card B": ID2LocationData(rname.dfc_a.value, 2210, "Dreamworld"),
    "Antigram - Reward Card C": ID2LocationData(rname.dfc_a.value, 2211, "Dreamworld"),
    
    # 2300: Bottomless Tower
    "Bottomless Tower - First Floor Card": ID2LocationData(rname.di_g.value, 2300, "Dreamworld"),
    "Bottomless Tower - First Floor Key": ID2LocationData(rname.di_c.value, 2301, "Dreamworld"),
    "Bottomless Tower - Second Floor Card": ID2LocationData(rname.di_d.value, 2302, "Dreamworld"),
    "Bottomless Tower - Second Floor Key": ID2LocationData(rname.di_f.value, 2303, "Dreamworld"),
    "Bottomless Tower - Blue Portal Card": ID2LocationData(rname.di_a.value, 2304, "Dreamworld"),
    "Bottomless Tower - Third Floor Spike Gates Card": ID2LocationData(rname.di_x.value, 2305, "Dreamworld"),
    "Bottomless Tower - Third Floor Key": ID2LocationData(rname.di_ab.value, 2306, "Dreamworld"),
    "Bottomless Tower - Third Floor Ice Square Card": ID2LocationData(rname.di_y.value, 2307, "Dreamworld"),
    "Bottomless Tower - Fourth Floor Key": ID2LocationData(rname.di_w.value, 2308, "Dreamworld"),
    "Bottomless Tower - Reward Card A": ID2LocationData(rname.di_z.value, 2309, "Dreamworld"),
    "Bottomless Tower - Reward Card B": ID2LocationData(rname.di_z.value, 2310, "Dreamworld"),
    "Bottomless Tower - Reward Card C": ID2LocationData(rname.di_z.value, 2311, "Dreamworld"),
    
    # 2400: Quietus
    "Quietus - Center Card": ID2LocationData(rname.da_n.value, 2400, "Dreamworld"),
    "Quietus - Alternating Floors Key": ID2LocationData(rname.da_f.value, 2401, "Dreamworld"),
    "Quietus - Tangled Wires Key": ID2LocationData(rname.da_j.value, 2402, "Dreamworld"),
    "Quietus - Push the Coil Key": ID2LocationData(rname.da_r.value, 2403, "Dreamworld"),
    "Quietus - Giant Mess Key": ID2LocationData(rname.da_v.value, 2404, "Dreamworld"),
    "Quietus - Northwest Vault Card": ID2LocationData(rname.da_g.value, 2405, "Dreamworld"),
    "Quietus - Northeast Vault Card": ID2LocationData(rname.da_i.value, 2406, "Dreamworld"),
    "Quietus - Southwest Vault Card": ID2LocationData(rname.da_s.value, 2407, "Dreamworld"),
    "Quietus - Southeast Vault Card": ID2LocationData(rname.da_u.value, 2408, "Dreamworld"),
    "Quietus - Reward Card A": ID2LocationData(rname.da_ab.value, 2409, "Dreamworld"),
    "Quietus - Reward Card B": ID2LocationData(rname.da_ab.value, 2410, "Dreamworld"),
    "Quietus - Reward Card C": ID2LocationData(rname.da_ab.value, 2411, "Dreamworld"),

    # 2500: Portal Worlds
    "Autumn Climb - Chest": ID2LocationData(rname.autumn_climb.value, 2500, "Portal Worlds"),
    "The Vault - Chest": ID2LocationData(rname.the_vault_b_center.value, 2501, "Portal Worlds"),
    "Painful Plain - Chest": ID2LocationData(rname.painful_plain.value, 2502, "Portal Worlds"),
    "Farthest Shore - Chest": ID2LocationData(rname.farthest_shore.value, 2503, "Portal Worlds"),
    "Scrap Yard - Chest": ID2LocationData(rname.scrap_yard_a.value, 2504, "Portal Worlds"),
    "Brutal Oasis - Chest": ID2LocationData(rname.brutal_oasis.value, 2505, "Portal Worlds"),
    "Former Colossus - Chest": ID2LocationData(rname.former_colossus_end.value, 2506, "Portal Worlds"),
    "Sand Crucible - Chest": ID2LocationData(rname.sand_crucible_a.value, 2507, "Portal Worlds"),
    "Ocean Castle - Chest": ID2LocationData(rname.ocean_castle.value, 2508, "Portal Worlds"),
    "Promenade Path - Chest": ID2LocationData(rname.promenade_path.value, 2509, "Portal Worlds"),
    "Maze of Steel - Chest": ID2LocationData(rname.maze_of_steel_a_left.value, 2510, "Portal Worlds"),
    "Wall of Text - Chest": ID2LocationData(rname.wall_of_text_b.value, 2511, "Portal Worlds"),
    "Lost City of Avlopp - Chest": ID2LocationData(rname.lost_city_c.value, 2512, "Portal Worlds"),
    "Northern End - Chest": ID2LocationData(rname.northern_end_f.value, 2513, "Portal Worlds"),
    "Moon Garden - Chest": ID2LocationData(rname.moon_garden_north.value, 2514, "Portal Worlds"),
    "Maze of Steel - Hint Sign": ID2LocationData(rname.maze_of_steel_e.value, 2515, "Hint Signs"),
    "Maze of Steel - Cipher Sign": ID2LocationData(rname.maze_of_steel_f.value, 2516, "Cipher Signs"),
    
    # 2600+: Misc Locations
    "Ludo City - Chest": ID2LocationData(rname.ludo_city_a.value, 2600, "Super Secrets"),
    "Bad Dream - Card": ID2LocationData(rname.bad_dream.value, 2602, "Super Secrets"),
    "Promised Remedy - That Guy Outfit": ID2LocationData(rname.pr_b.value, 2603, "Super Secrets"),
    "Nowhere - Left Hint Sign": ID2LocationData(rname.nowhere.value, 2604, "Hint Signs"),
    "Nowhere - Right Hint Sign": ID2LocationData(rname.nowhere.value, 2605, "Cipher Signs"),
    "Nowhere - Cipher Sign": ID2LocationData(rname.nowhere.value, 2606, "Cipher Signs"),
    "Ludo City - Cipher Sign": ID2LocationData(rname.ludo_city_b.value, 2607, "Cipher Signs"),
    "Abyssal Plane - Shard Hint Sign": ID2LocationData(rname.abyssal_plain.value, 2608, "Hint Signs"),
    "Abyssal Plane - Roll Hint Sign": ID2LocationData(rname.abyssal_plain.value, 2609, "Hint Signs"),
    "Abyssal Plane - Drop Table Hint Sign": ID2LocationData(rname.abyssal_plain.value, 2610, "Hint Signs"),
    "Abyssal Plane - Boss Hint Sign": ID2LocationData(rname.abyssal_plain.value, 2611, "Hint Signs"),
    "Place From Younger Days - Cipher Sign": ID2LocationData(rname.place_d.value, 2612, "Cipher Signs"),
    "Promised Remedy - E Cipher Sign": ID2LocationData(rname.pr_e.value, 2613, "Cipher Signs"),
    "Promised Remedy - F Cipher Sign": ID2LocationData(rname.pr_f.value, 2614, "Cipher Signs"),
    "Promised Remedy - G Left Cipher Sign": ID2LocationData(rname.pr_g.value, 2615, "Cipher Signs"),
    "Promised Remedy - G Middle Cipher Sign": ID2LocationData(rname.pr_g.value, 2616, "Cipher Signs"),
    "Promised Remedy - G Right Cipher Sign": ID2LocationData(rname.pr_g.value, 2617, "Cipher Signs"),
    "Promised Remedy - M Cipher Sign": ID2LocationData(rname.pr_m.value, 2618, "Cipher Signs"),
    "Promised Remedy - N Cipher Sign": ID2LocationData(rname.pr_n.value, 2619, "Cipher Signs"),
    "Promised Remedy - NAAQ BLX Sign": ID2LocationData(rname.pr_q.value, 2620, "Cipher Signs")
}

event_location_table: Dict[str, ID2LocationData] = {
    "Flooded Basement K South Door": ID2LocationData(rname.d5_k_top.value, None),
    "Flooded Basement Crossway Access": ID2LocationData(rname.d5_o_top.value, None),
    "Grand Library K Left Door": ID2LocationData(rname.d8_k_left.value, None),
    "Grand Library K Right Door": ID2LocationData(rname.d8_k_right.value, None),
    "Sunken Labyrinth Q Blocks": ID2LocationData(rname.s1_q_right.value, None, "Secret Dungeons"),
    "Wizardry Lab Southwest Generator Activated": ID2LocationData(rname.df_ae.value, None, "Dreamworld"),
    "Wizardry Lab Southeast Generator Activated": ID2LocationData(rname.df_ag.value, None, "Dreamworld"),
    "Wizardry Lab Northwest Generator Activated": ID2LocationData(rname.df_w.value, None, "Dreamworld"),
    "Wizardry Lab Northeast Generator Activated": ID2LocationData(rname.df_aa.value, None, "Dreamworld"),
    "Wizardry Lab Northeast Circuit Connected": ID2LocationData(rname.df_e.value, None, "Dreamworld"),
    "Wizardry Lab Southwest Circuit Connected": ID2LocationData(rname.df_x.value, None, "Dreamworld"),
    "Wizardry Lab Southeast Circuit Connected": ID2LocationData(rname.df_z.value, None, "Dreamworld"),
    "Syncope Chamber Switching": ID2LocationData(rname.dd_am.value, None, "Dreamworld"),
    "Syncope E Block Available": ID2LocationData(rname.dd_e.value, None, "Dreamworld"),
    "Syncope Garden Block Moved": ID2LocationData(rname.dd_w.value, None, "Dreamworld"),
    "Syncope West Clock Wound": ID2LocationData(rname.dd_y.value, None, "Dreamworld"),
    "Syncope East Clock Wound": ID2LocationData(rname.dd_ab.value, None, "Dreamworld"),
    "Syncope North Clock Wound": ID2LocationData(rname.dd_l.value, None, "Dreamworld"),
    "Syncope Piano Code Found": ID2LocationData(rname.dd_w.value, None, "Dreamworld"),
    "Antigram Left Switch Pressed": ID2LocationData(rname.dfc_h_left.value, None, "Dreamworld"),
    "Antigram Right Switch Pressed": ID2LocationData(rname.dfc_h_right.value, None, "Dreamworld"),
    "Bottomless Tower First Floor Green Fire Obtained": ID2LocationData(rname.di_o.value, None, "Dreamworld"),
    "Bottomless Tower Second Floor Green Fire Obtained": ID2LocationData(rname.di_q.value, None, "Dreamworld"),
    "Bottomless Tower Third Floor Green Fire Obtained": ID2LocationData(rname.di_aa.value, None, "Dreamworld"),
    "Quietus Northwest Crystal": ID2LocationData(rname.da_a.value, None, "Dreamworld"),
    "Quietus Northeast Crystal": ID2LocationData(rname.da_c.value, None, "Dreamworld"),
    "Quietus Southwest Crystal": ID2LocationData(rname.da_w.value, None, "Dreamworld"),
    "Quietus Southeast Crystal": ID2LocationData(rname.da_aa.value, None, "Dreamworld"),
    "Quietus Central Crystal": ID2LocationData(rname.da_n.value, None, "Dreamworld"),
    "Finished Wizardry Lab": ID2LocationData(rname.dd_ah.value, None, "Dreamworld"),
    "Finished Syncope": ID2LocationData(rname.dd_ao.value, None, "Dreamworld"),
    "Finished Antigram": ID2LocationData(rname.dfc_a.value, None, "Dreamworld"),
    "Finished Bottomless Tower": ID2LocationData(rname.di_z.value, None, "Dreamworld"),
    "The Vault West Switch": ID2LocationData(rname.the_vault_b_left.value, None, "Portal Worlds"),
    "The Vault East Switch": ID2LocationData(rname.the_vault_b_right.value, None, "Portal Worlds"),
    "Scrap Yard West Block": ID2LocationData(rname.scrap_yard_c_left.value, None, "Portal Worlds"),
    "Scrap Yard East Block": ID2LocationData(rname.scrap_yard_c_right.value, None, "Portal Worlds"),
}

location_name_to_id: Dict[str, int] = {name: location_base_id + data.location_id_offset for name, data in location_table.items()}

location_name_groups: Dict[str, Set[str]] = {}
for loc_name, loc_data in location_table.items():
    loc_group_name = loc_name.split(" - ", 1)[0]
    location_name_groups.setdefault(loc_group_name, set()).add(loc_name)
    if loc_data.location_group:
        location_name_groups.setdefault(loc_data.location_group, set()).add(loc_name)
for event_name, event_data in event_location_table.items():
    if event_data.location_group:
        location_name_groups.setdefault(event_data.location_group, set()).add(event_name)

